export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS seo_merchants (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',
    operator_user_ids TEXT NOT NULL DEFAULT '[]',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS seo_locations (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    display_name TEXT NOT NULL,
    timezone TEXT,
    external_identities TEXT NOT NULL DEFAULT '{}',
    readiness_status TEXT NOT NULL,
    missing_requirements TEXT NOT NULL DEFAULT '[]',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(merchant_id, slug)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_locations_merchant ON seo_locations(merchant_id)`,

  `CREATE TABLE IF NOT EXISTS seo_tasks (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    location_id TEXT,
    task_type TEXT NOT NULL,
    source TEXT NOT NULL,
    priority TEXT NOT NULL,
    impact TEXT NOT NULL,
    owner_id TEXT,
    due_at TEXT,
    status TEXT NOT NULL,
    evidence_state TEXT NOT NULL,
    task_revision INTEGER NOT NULL,
    state_version INTEGER NOT NULL,
    title TEXT NOT NULL,
    execution_spec TEXT NOT NULL,
    execution_spec_hash TEXT NOT NULL,
    required_evidence_types TEXT NOT NULL DEFAULT '[]',
    revisions TEXT NOT NULL DEFAULT '[]',
    evidence_refs TEXT NOT NULL DEFAULT '[]',
    approval_decisions TEXT NOT NULL DEFAULT '[]',
    events TEXT NOT NULL DEFAULT '[]',
    conversation_links TEXT NOT NULL DEFAULT '[]',
    agent_run_links TEXT NOT NULL DEFAULT '[]',
    mutation_keys TEXT NOT NULL DEFAULT '{}',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_merchant_status_due ON seo_tasks(merchant_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_owner_status_due ON seo_tasks(owner_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_merchant_updated ON seo_tasks(merchant_id, updated_at DESC)`,

  `CREATE TABLE IF NOT EXISTS seo_agent_runs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    run_type TEXT NOT NULL,
    goal TEXT,
    status TEXT NOT NULL,
    core_run_id TEXT,
    core_status TEXT,
    input_message TEXT NOT NULL,
    output TEXT,
    error TEXT,
    error_code TEXT,
    token_usage TEXT NOT NULL DEFAULT '{}',
    artifact_path TEXT,
    artifact_sha256 TEXT,
    evidence_id TEXT,
    evidence_skipped_reason TEXT,
    triggered_by TEXT NOT NULL,
    triggered_at TEXT NOT NULL,
    last_polled_at TEXT,
    completed_at TEXT,
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_task_created ON seo_agent_runs(task_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON seo_agent_runs(status)`,
];
