export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS seo_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL,
    identity_type TEXT NOT NULL CHECK (identity_type IN ('HUMAN', 'SERVICE')),
    permissions TEXT NOT NULL DEFAULT '[]',
    password_hash TEXT,
    status TEXT NOT NULL,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TEXT,
    last_login_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_users_status ON seo_users(status)`,

  `CREATE TABLE IF NOT EXISTS seo_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_user ON seo_sessions(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON seo_sessions(expires_at)`,

  `CREATE TABLE IF NOT EXISTS seo_merchants (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',
    operator_user_ids TEXT NOT NULL DEFAULT '[]',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS seo_locations (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    display_name TEXT NOT NULL,
    timezone TEXT,
    external_identities TEXT NOT NULL DEFAULT '{}',
    readiness_status TEXT NOT NULL,
    missing_requirements TEXT NOT NULL DEFAULT '[]',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(merchant_id, slug)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_locations_merchant ON seo_locations(merchant_id)`,

  `CREATE TABLE IF NOT EXISTS seo_tasks (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    location_id TEXT,
    task_type TEXT NOT NULL,
    source TEXT NOT NULL,
    priority TEXT NOT NULL,
    impact TEXT NOT NULL,
    owner_id TEXT,
    due_at TEXT,
    status TEXT NOT NULL,
    evidence_state TEXT NOT NULL,
    task_revision INTEGER NOT NULL,
    state_version INTEGER NOT NULL,
    title TEXT NOT NULL,
    execution_spec TEXT NOT NULL,
    execution_spec_hash TEXT NOT NULL,
    required_evidence_types TEXT NOT NULL DEFAULT '[]',
    revisions TEXT NOT NULL DEFAULT '[]',
    evidence_refs TEXT NOT NULL DEFAULT '[]',
    approval_decisions TEXT NOT NULL DEFAULT '[]',
    events TEXT NOT NULL DEFAULT '[]',
    conversation_links TEXT NOT NULL DEFAULT '[]',
    agent_run_links TEXT NOT NULL DEFAULT '[]',
    mutation_keys TEXT NOT NULL DEFAULT '{}',
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_merchant_status_due ON seo_tasks(merchant_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_owner_status_due ON seo_tasks(owner_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_merchant_updated ON seo_tasks(merchant_id, updated_at DESC)`,

  /** 阶段运行：归属于（商户，地点，阶段），不挂在 task 上。task_id 仅作溯源
   * （Plan 转出的任务回指来源运行），永远可空。 */
  `CREATE TABLE IF NOT EXISTS seo_agent_runs (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    location_id TEXT,
    stage TEXT NOT NULL,
    task_id TEXT,
    run_type TEXT NOT NULL,
    goal TEXT,
    status TEXT NOT NULL,
    core_run_id TEXT,
    core_status TEXT,
    input_message TEXT NOT NULL,
    output TEXT,
    error TEXT,
    error_code TEXT,
    token_usage TEXT NOT NULL DEFAULT '{}',
    triggered_by TEXT NOT NULL,
    triggered_at TEXT NOT NULL,
    last_polled_at TEXT,
    completed_at TEXT,
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_merchant_stage ON seo_agent_runs(merchant_id, stage, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON seo_agent_runs(status)`,

  /** 交付物：一文件一行。SUMMARY = 运行正文落盘；ATTACHMENT = agent 返回的附件；
   * MANUAL = 运营手工上传兜底。按 id 服务下载（数组下标会因补下载而错位）。
   * id 由 (run_id, 来源) 决定性生成，终态重放时 INSERT OR REPLACE 天然幂等。 */
  `CREATE TABLE IF NOT EXISTS seo_run_deliverables (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    file_id TEXT,
    file_name TEXT NOT NULL,
    content_type TEXT,
    size INTEGER,
    title TEXT,
    description TEXT,
    sha256 TEXT,
    local_path TEXT,
    remote_url TEXT,
    downloaded_at TEXT,
    download_error TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_deliverables_run ON seo_run_deliverables(run_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_deliverables_sha ON seo_run_deliverables(sha256)`,

  `CREATE TABLE IF NOT EXISTS seo_merchant_questionnaires (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    share_slug TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    base_info TEXT NOT NULL DEFAULT '{}',
    questions TEXT NOT NULL DEFAULT '[]',
    answers TEXT,
    send_count INTEGER NOT NULL DEFAULT 0,
    sent_at TEXT,
    last_sent_at TEXT,
    filled_at TEXT,
    creation_idempotency_key TEXT,
    request_fingerprint TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_questionnaires_merchant_created ON seo_merchant_questionnaires(merchant_id, created_at DESC)`,
];
