apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connexup-seo-ops-uat
resources:
  - namespace.yaml
  - configmap.yaml
  - artifacts-pvc.yaml
  - api.yaml
  - worker.yaml
  - scheduler.yaml
  - frontend.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/canqiang/connexup-seo-ops-server
    newTag: uat
  - name: ghcr.io/canqiang/connexup-seo-ops-frontend
    newTag: uat
